server:
  port: 8080
  servlet:
    context-path: /ex
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/j10jb2?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: sjjqwe123...
  messages:
    basename: j10
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB
mybatis-plus:
  type-aliases-package: 'com.j10.exercise.bean'
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl